config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/pokemon'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
require 'rubygems'
require 'httparty'
class HomeController < ApplicationController
  def index
    
    
   

  end

  def pokemon
    #@result = HTTParty.get('https://pokeapi.co/api/v2/pokemon/1')
    @result = HTTParty.get('https://pokeapi.co/api/v2/pokemon?offset=0&limit=20')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Pokemons link</h1>

<%= link_to 'Get Pokemons', home_pokemon_path  %>

app/views/home/pokemon.html.erb
<h1>List of Pokemons</h1>

<br /> <br />

<ul>

<li>
<%= JSON.parse(@result.body)  %>
</li> 

</ul>


<%= (@result.code)  %>

<br /> <br />

<%= (@result.message)  %>

<br /> <br />


<%=(@result.headers.inspect) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Api5</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>